### ISSUE TITLE
SimpreRead examle fails

### ISSUE THREAD

**Issue by klavatron** [michalhol/ps2kbdlib#4]
I'm using logic level converter. I've tried two examples. ReadRawData works ok. SimpreRead read some keys and fails after few seconds.

**Comment by cubicap** [comment]
Does it fail after some time or after a few keystrokes?

**Comment by klavatron** [comment]
My bad. I reconnected everything and now it works without problems. Probably there was problem with breadboard contact or with keyboard cable.
