### ISSUE TITLE
Working on ESP8266 too?

### ISSUE THREAD

**Issue by edugimeno** [michalhol/ps2kbdlib#5]
I don't know if there are many differences between ESP32 and ESP8266 but I need to connect a PS2 Keyboard to a Wemos D1 board (ESP8266 based)  and as soon as I add the #include and initialization with this library, my board resets after 1-2 seconds...
Is there any change needed to make it work with 8266?
I don't even have a keyboard connected to it yet, but Im assuming it wouldn't crash due to it, would it?

Thanks

**Comment by cubicap** [comment]
I don't think, the library uses anything specific for ESP32.

Are you using Arduino framework? And do you get any message from the ESP8266 through serial?

The only thing I can think of is in PS2Kbd.cpp on lines 335 and 336 you may try to change OUTPUT_OPEN_DRAIN to INPUT_PULLUP.

```
void PS2Kbd::begin() {
    pinMode(dataPin, INPUT_PULLUP);
    pinMode(clkPin, INPUT_PULLUP);
```

I was not working on this part of the lib, so I can not say for sure, whether or not will it help.

**Comment by edugimeno** [comment]
Thanks for getting back. No, all I get on the serial console is the usual bootup msg:
~ld

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld

I realized that I can (step by step) :
#include <PS2Kbd.h>: No reboots
PS2Kbd keyboard(12, 13);: No reboots with only the constructor

But as soon as I uncomment the 
  keyboard.begin();

it starts rebooting. 

I tried the changes you offered and re compiled but same effect.
Let me know if there's any other test I can do for you.
Also what pins can I use for this? Right now I have set 12 &13 for the keyboard (but like I said KB is not connected yet) but I tried other pins with same result

**Comment by cubicap** [comment]
For the data pin, you can use any pin and for clock pin, you can use any pin, as long as it supports interrupts (afaik, all pins except GPIO16 support interrupts). So the pins you use are using should not be a problem. 

You can try to debug the issue by modifying the PS2Kbd::begin() method. Again, file PS2Kbd.cpp, beginning with line 334. You can add a few debug prints to find out, at which line it crashes. Or, if it does not work out, you can try commenting stuff in the PS2Kbd::begin() method.

**Comment by edugimeno** [comment]
Did you see that the reset cause was 2, which usually means wdt reset? 
Do you think this would relate?
See this other thread:
https://github.com/esp8266/Arduino/issues/3241
It mentions that some functions programmed for ESP can't be locking and they would have to include a "yield" sentence in order to avoid WDT reboots....

**Comment by cubicap** [comment]
I missed the reset cause.

In the issue, you have linked, always figures a loop, which in this case is not. 

Weird is, that you do not get any stack trace (see [here](https://arduino-esp8266.readthedocs.io/en/latest/faq/a02-my-esp-crashes.html)).

Also, the article, I linked, mentions something about interrupts on ESP8266. It may be possible to fix by modifying interruptHandler() method or the PS2Kbd::kbdInterruptX() series to work properly on ESP8266. It is all mentioned there.

I have never worked with ESP8266, so I can really just guess at this point.

To prove my point that the error is caused by the interrupts, can you try to comment out the whole block of ifs, where the interrupts are attached?

**Comment by edugimeno** [comment]
I got some improvement...
Once I started the serial monitor (my sketch isn't using it so I wasn't paying attention to it) and added the Serial.begin, I saw a warning: "ISR not in IRAM"
After looking up some forums I added "ICACHE_RAM_ATTR" before every interrupt handler declaration
This let me use keyboard.begin() and it went thru it succesfully.
But then when I uncommented the following line:
`while (!fin)
    if (keyboard.available())
      fin = (keyboard.read() == '\n');`
it got stuck again at that step...
Any hint on this?

Thanks

**Comment by cubicap** [comment]
Nice.

It is likely a case of the busy loop mentioned in the issue, you linked earlier. Possibly adding `yield();` in the loop will fix that.

**Comment by edugimeno** [comment]
Ok, right now my sketch is not rebooting, but it's still close to 25% developed. And I don't even have a real PS2 keyboard connected to it. 
What I've done so far is:
**Library**: Added ICACHE_RAM_ATTR to all interrupt handlers
**Code**: Added Yield() to one look that awaits for an available key

At this point my library os tweaked and my sketc has extra lines that I don't really reach to fully understand why.... Im afraid my code gest unstable as I keep developing.
Fingers crossed....
Thanks

**Comment by cubicap** [comment]
Good luck with the project. 

Also, could you please make a fork of this repository with the fixed support of ESP8266? I could at least link the version here or possibly merge them to support both platforms.

**Comment by edugimeno** [comment]
I can definitely do it, but 
1) I've nover worked with github, Im a fast learner and I can probably do it without further explanation
2) My code isn't really tested yet, I mean, I know it doesn't crash anymore but a) I have no keyboard connected to it b) Im still missing most of the functionality

Wouldn't you wait until I can have most of it tested and with a keyboard?
I can probably meet that point by end of next week

Let me know what you prefer
Thanks

**Comment by cubicap** [comment]
Time really does not matter, when you will have the code tested, let me know here.

The easiest way to get code to Github (on Windows), is to fork the repository, clone it to your PC with Github desktop, make the changes, and commit+push them to the repository. Or, if you did not change much, you can, once again, fork the repo and then edit the files online.

Thank you

**Comment by edugimeno** [comment]
EDITED (if anyone read it before). I works! I tried it with my Wemos D1 R1 /ESP8266) and a real PS/2 Keyboard thru a level shifter and it works right away!! Glad I can use as I found no other version of this library anywhere.
I will try to fork it asap, I need to finish my code soon too!
Thanks for this library!

**Comment by cubicap** [comment]
Nice!
